# Generated by Django 4.0.5 on 2022-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_aula_slug_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
