# Generated by Django 4.0.5 on 2022-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_aula_slug_alter_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
