# Generated by Django 4.0.5 on 2022-06-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_aula_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='slug',
            new_name='slug_aula',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='slug',
            new_name='slug_curso',
        ),
    ]
