# Generated by Django 4.0.5 on 2022-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_rename_slug_aula_slug_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug_aula',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug_aula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug_curso',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug_curso'),
        ),
    ]
